package com.filesplitter.FileSplitter.constants;

public enum PrimeColumn {
  CARRIER_ID(0),
  ACCT_NUMBER(1),
  GROUP_NUMBER(2),
  CBC(3),
  FULL_PATIENT_ID(4),
  PATIENT_LAST_NAME(5),
  PATIENT_FIRST_NAME(6),
  INDIVIDUAL_MARKET_INDICATOR(7),
  DUAL_ADJUDICATION_INDICATOR(8),
  //  REFUND_DUE(9),
  //  FULL_DATE_OF_SERVICE(10),
  //  REAL_CLAIM_NUMBER(11),
  //  REAL_CLAIM_SEQ_NUMBER(12),
  //  REAL_CLAIM_STATUS(13),
  //  ALTERNATE_CLAIM_NUMBER(14),
  //  ALTERNATE_CLAIM_SEQ_NUMBER(15),
  //  ALTERNATE_CLAIM_STATUS(16),
  FULL_DATE_OF_TRANSACTION(17),
  TRANSACTION_SIGN(18),
  MEDICAL_OR_PHARMACY(19),
  DEDUCTIBLE_ACCUM_CODE(20),
  //  DEDUCTIBLE_ADJUSTMENT_HANDLING_OVERRIDE(21),
  DEDUCTIBLE_ADJUSTMENT_REASON_CODE(22),
  DEDUCTIBLE_REAL_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(23),
  DEDUCTIBLE_ALTERNATE_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(24),
  OUT_OF_POCKET_ACCUM_CODE(25),
  //  OUT_OF_POCKET_ADJUSTMENT_HANDLING_OVERRIDE(26),
  OUT_OF_POCKET_ADJUSTMENT_REASON_CODE(27),
  OUT_OF_POCKET_REAL_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(28),
  OUT_OF_POCKET_ALTERNATE_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(29),
  //  LIFETIME_MAX_ACCUM_CODE(30),
  //  LIFETIME_MAX_ADJUSTMENT_HANDLING_OVERRIDE(31),
  //  LIFETIME_MAX_ADJUSTMENT_REASON_CODE(32),
  //  LIFETIME_MAX_REAL_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(33),
  //  LIFETIME_MAX_ALTERNATE_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(34),
  //  BENEFIT_MAX_ACCUM_CODE(35),
  //  BENEFIT_MAX_ADJUSTMENT_HANDLING_OVERRIDE(36),
  //  BENEFIT_MAX_ADJUSTMENT_REASON_CODE(37),
  //  BENEFIT_REAL_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(38),
  //  BENEFIT_ALTERNATE_DOLLAR_AMOUNT_NEEDED_FROM_PRIME(39),
  DESCRIPTION(40),
  //  OPERATOR_ID(41),
  //  ADDITIONAL_NOTES_OF_EXPLANATION(42),
  //  RX_NUMBER(43),
  //  PRESCRIBER_ID(44),
  //  SN_ISSUE_TRACKING_ID(45),
  //  VARIANT_COMPONENT_ID(46),
  //  POST_PROCESSING_ERRORS(47)
  ;

  private final int index;

  PrimeColumn(int index) {
    this.index = index;
  }

  public int getIndex() {
    return index;
  }
}